import pandas as pd
import argparse
import os

def extract_put_viro_and_plv(input_file):

    df = pd.read_csv(input_file, sep='\t')
    length = df['Genome'].str.split('_').str[3]
    df['length'] = pd.to_numeric(length, errors = 'coerce')

    df = df[df['length'] >= 10000]

    #Selecting only the possible virophage sequences predicted by run_virophage_affi.pl 
    viro_df = df[df['Assignation (Class;Family)'] != 'Possible_PLV']
    viro_df = viro_df['Genome'].to_list()

    #Selecting only the possible PLV sequences predicted by run_virophage_affi.pl
    plv_df = df[df['Assignation (Class;Family)'] == 'Possible_PLV']  
    plv_df = plv_df['Genome'].to_list()

    return viro_df, plv_df

def remove_run_virophage_affi_temp_files(input_file_path):
    cmd = f""""
    rm {os.path.dirname(input_file_path)}/*.faa \
    rm {os.path.dirname(input_file_path)}/*.gff \
    rm {os.path.dirname(input_file_path)}/*best_markers* \
    rm {os.path.dirname(input_file_path)}/*cds_to_family* \
    rm {os.path.dirname(input_file_path)}/*cds-vs-marker* \
    rm {os.path.dirname(input_file_path)}/*all_markers* \
    rm {os.path.dirname(input_file_path)}/*PLV_Marker* 
    """

    os.system(cmd)

def main():
    parser = argparse.ArgumentParser(description="Extracting both putative sequences from virophages and polinton viruses")
    parser.add_argument("-i", "--input", help='Input table containg virophage and PLV assignment')
    parser.add_argument("-o", "--output_dir", help='DIrectory to store tables containg the names of putative virophages and plvs.')
    args = parser.parse_args()

    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)

    virophage_list, plv_list = extract_put_viro_and_plv(args.input)
    
    #Putative Virophage list
    with open(f"{args.output_dir}/putative_virophage_list.tsv", "w") as viro_file:
        viro_file.write("\n".join(str(item) for item in virophage_list) + "\n")

    #Putative PLV list
    with open(f"{args.output_dir}/putative_plv_list.tsv", "w") as plv_file:
        plv_file.write("\n".join(str(item) for item in plv_list) + "\n")

    #Remove temporary files generated by run_virophage_affi.pl
    remove_run_virophage_affi_temp_files(args.input)

if __name__ == "__main__":
    main()
    